// web/src/pages/Inbox.tsx
import { useState, useEffect, useRef, useCallback } from "react"
import { Link, useParams, useLocation, useNavigate } from "react-router-dom"
import { Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Collapsible } from "@/components/ui/collapsible"
import { Copy, ChevronDown, Shuffle, Trash2 } from "lucide-react"
import { validateMailbox, randomMailbox } from "@/lib/utils"

interface DecodedPayload {
  type: "text" | "json" | "binary" | "invalid" | "ping"
  content: string
  raw: string
}

interface Message {
  id: string
  message_hex?: string
  received_at?: number
  message_type?: string
  data_b64: string
  peer_ip?: string
  payload: DecodedPayload
}

type StatusLevel = "idle" | "good" | "warn" | "bad"

function toHex(bytes: Uint8Array): string {
  let out = ""
  for (let i = 0; i < bytes.length; i++) {
    if (i && i % 16 === 0) out += "\n"
    else if (i && i % 2 === 0) out += " "
    out += bytes[i].toString(16).padStart(2, "0")
  }
  return out
}

function decodePayload(b64: string, messageType?: string): DecodedPayload {
  if (messageType === "ping") {
    return { type: "ping", content: "", raw: "" }
  }
  try {
    const bin = atob(b64)
    const bytes = new Uint8Array(bin.length)
    for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i) & 0xff

    let text: string | null = null
    try {
      text = new TextDecoder("utf-8", { fatal: true }).decode(bytes)
    } catch { /* not utf8 */ }

    const printable = text && text.length > 0 && !/[\x00-\x08\x0b\x0c\x0e-\x1f]/.test(text)
    if (text && printable) {
      const trimmed = text.trim()
      if (
        (trimmed.startsWith("{") && trimmed.endsWith("}")) ||
        (trimmed.startsWith("[") && trimmed.endsWith("]"))
      ) {
        try {
          const parsed = JSON.parse(text)
          return { type: "json", content: JSON.stringify(parsed, null, 2), raw: b64 }
        } catch { /* not valid json */ }
      }
      return { type: "text", content: text, raw: b64 }
    }
    return { type: "binary", content: toHex(bytes), raw: b64 }
  } catch (e) {
    return { type: "invalid", content: `Invalid base64: ${e}`, raw: b64 }
  }
}

function formatDate(date: Date): string {
  const d = String(date.getDate()).padStart(2, "0")
  const m = String(date.getMonth() + 1).padStart(2, "0")
  const y = date.getFullYear()
  const H = String(date.getHours()).padStart(2, "0")
  const M = String(date.getMinutes()).padStart(2, "0")
  const S = String(date.getSeconds()).padStart(2, "0")
  return `${d}.${m}.${y}, ${H}:${M}:${S}`
}

function formatReceivedAt(value: unknown): string {
  const numeric = typeof value === "number" ? value : Number(value)
  if (!Number.isFinite(numeric)) return "Unknown time"
  const date = new Date(numeric)
  if (Number.isNaN(date.getTime())) return "Unknown time"
  return formatDate(date)
}

function normalizeHttp(base: string, fallback: string): string {
  const h = (base || "").trim()
  if (!h) return fallback
  if (h.startsWith("http://") || h.startsWith("https://")) return h
  if (h.includes("dnsm.re")) return "https://" + h
  const scheme = location.protocol === "https:" ? "https://" : "http://"
  return scheme + h
}

function toWsUrl(httpBase: string): string {
  const u = new URL(httpBase)
  u.protocol = u.protocol === "https:" ? "wss:" : "ws:"
  return u.toString().replace(/\/$/, "")
}

const COLLAPSE_LINE_THRESHOLD = 12
const COLLAPSE_CHAR_THRESHOLD = 1000

function isLongContent(content: string): boolean {
  return content.length > COLLAPSE_CHAR_THRESHOLD ||
    content.split("\n").length > COLLAPSE_LINE_THRESHOLD
}

interface WasmModule {
  default: () => Promise<void>
  domains_for_string_with_mailbox: (input: string, zone: string, mailbox: string) => string[]
}

export function Inbox() {
  const { id } = useParams()
  const location = useLocation()
  const navigate = useNavigate()

  const defaultHost = window.location.hostname === "localhost" || window.location.hostname === "127.0.0.1"
    ? "127.0.0.1:8787" : "ws.dnsm.re"

  const [host, setHost] = useState(defaultHost)
  const [mailbox, setMailbox] = useState("")
  const [zone, setZone] = useState("k.dnsm.re")
  const [messages, setMessages] = useState<Message[]>([])
  const [status, setStatus] = useState<{ text: string; level: StatusLevel }>({ text: "Idle", level: "idle" })
  const [expandedMessages, setExpandedMessages] = useState<Set<string>>(new Set())
  const [wasmModule, setWasmModule] = useState<WasmModule | null>(null)
  const [genMessage, setGenMessage] = useState("")
  const [genDomains, setGenDomains] = useState<string[]>([])
  const [genError, setGenError] = useState("")

  const wsRef = useRef<WebSocket | null>(null)
  const reconnectTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)
  const reconnectDelayRef = useRef(1000)
  const generationRef = useRef(0)
  const abortRef = useRef<AbortController | null>(null)
  const activeMailboxRef = useRef("")
  const activeHostRef = useRef("")

  const parentZone = zone.split(".").slice(1).join(".") || zone
  const mailboxZone = `m.${parentZone}`

  const scheduleReconnect = useCallback(() => {
    if (reconnectTimerRef.current) clearTimeout(reconnectTimerRef.current)
    reconnectTimerRef.current = setTimeout(
      () => connect({ mailbox: activeMailboxRef.current, host: activeHostRef.current }),
      reconnectDelayRef.current,
    )
    reconnectDelayRef.current = Math.min(reconnectDelayRef.current * 2, 20000)
    setStatus({ text: `Reconnecting in ${Math.round(reconnectDelayRef.current / 1000)}s...`, level: "warn" })
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const connect = useCallback(async (opts?: { mailbox?: string; host?: string; replace?: boolean }) => {
    const target = opts?.mailbox || mailbox
    const effectiveHost = opts?.host || host
    const validated = validateMailbox(target)
    if (!validated) {
      setStatus({ text: "Mailbox must be 12 lowercase hex chars", level: "bad" })
      return
    }

    const gen = ++generationRef.current
    if (abortRef.current) abortRef.current.abort()
    const abort = new AbortController()
    abortRef.current = abort

    activeMailboxRef.current = validated
    activeHostRef.current = effectiveHost
    setMailbox(validated)

    const isNonDefaultHost = effectiveHost !== defaultHost
    const search = isNonDefaultHost ? `?host=${encodeURIComponent(effectiveHost)}` : ""
    const targetUrl = `/inbox/${validated}${search}`
    if (targetUrl !== location.pathname + location.search) {
      navigate(targetUrl, { replace: opts?.replace ?? false })
    }

    setStatus({ text: "Connecting...", level: "warn" })
    setMessages([])

    const prevWs = wsRef.current
    wsRef.current = null
    if (prevWs && (prevWs.readyState === WebSocket.OPEN || prevWs.readyState === WebSocket.CONNECTING)) {
      try { prevWs.close() } catch { /* ignore */ }
    }
    if (reconnectTimerRef.current) {
      clearTimeout(reconnectTimerRef.current)
      reconnectTimerRef.current = null
    }
    reconnectDelayRef.current = 1000

    let wsBase: string
    let backlogOk = false
    let timedOut = false
    try {
      const fallback = `${window.location.protocol}//${window.location.host}`
      const httpBase = normalizeHttp(effectiveHost, fallback)
      wsBase = toWsUrl(httpBase)

      const timeout = setTimeout(() => { timedOut = true; abort.abort() }, 10000)
      try {
        const url = `${httpBase.replace(/\/$/, "")}/api/mailbox/${validated}/messages`
        const res = await fetch(url, { signal: abort.signal })
        if (gen !== generationRef.current) return
        if (res.ok) {
          const arr = await res.json()
          if (gen !== generationRef.current) return
          if (Array.isArray(arr)) {
            backlogOk = true
            setMessages(arr.reverse().map((m: { data_b64: string; message_type?: string }) => ({
              ...m,
              payload: decodePayload(m.data_b64, m.message_type),
            } as Message)))
          }
        } else {
          setStatus({ text: `Backlog fetch failed: HTTP ${res.status}`, level: "warn" })
        }
      } catch (e) {
        if (gen !== generationRef.current) return
        if (timedOut) {
          setStatus({ text: "History fetch timed out — showing live messages only", level: "warn" })
        } else if (!abort.signal.aborted) {
          setStatus({ text: `Backlog fetch error: ${e}`, level: "warn" })
        }
      } finally {
        clearTimeout(timeout)
      }
    } catch (e) {
      if (gen !== generationRef.current) return
      setStatus({ text: `Invalid host: ${e}`, level: "bad" })
      return
    }

    if (gen !== generationRef.current) return

    try {
      const ws = new WebSocket(`${wsBase}/ws/${validated}`)
      wsRef.current = ws

      ws.addEventListener("open", () => {
        if (gen !== generationRef.current) { ws.close(); return }
        setStatus(backlogOk
          ? { text: "Connected", level: "good" }
          : { text: "Connected — history unavailable", level: "warn" })
        reconnectDelayRef.current = 1000
      })
      ws.addEventListener("close", () => {
        if (gen !== generationRef.current) return
        setStatus({ text: "Disconnected", level: "warn" })
        scheduleReconnect()
      })
      ws.addEventListener("error", () => {
        if (gen !== generationRef.current) return
        setStatus({ text: "WebSocket error", level: "bad" })
      })
      ws.addEventListener("message", (ev) => {
        if (gen !== generationRef.current) return
        try {
          const m = JSON.parse(ev.data)
          const msg: Message = { ...m, payload: decodePayload(m.data_b64, m.message_type) }
          setMessages((prev) => [...prev, msg])
        } catch { /* ignore */ }
      })
    } catch (e) {
      if (gen !== generationRef.current) return
      setStatus({ text: `WS init failed: ${e}`, level: "bad" })
      scheduleReconnect()
    }
  }, [host, mailbox, defaultHost, navigate, scheduleReconnect, location.pathname, location.search])

  useEffect(() => {
    window.scrollTo({ top: document.documentElement.scrollHeight })
  }, [messages])

  useEffect(() => {
    import("@/lib/pkg-web/dnsm.js").then(async (mod) => {
      await mod.default()
      setWasmModule(mod as unknown as WasmModule)
    }).catch(() => { /* wasm load failed */ })

    return () => {
      generationRef.current++
      if (abortRef.current) abortRef.current.abort()
      const ws = wsRef.current
      wsRef.current = null
      if (ws) try { ws.close() } catch { /* ignore */ }
      if (reconnectTimerRef.current) clearTimeout(reconnectTimerRef.current)
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const routeSearch = location.search
  useEffect(() => {
    const params = new URLSearchParams(routeSearch)
    const hostParam = params.get("host")

    let mb = ""
    if (id && validateMailbox(id)) {
      mb = id
    }
    if (!mb) {
      const mailboxParam = params.get("mailbox")
      if (mailboxParam) mb = mailboxParam
    }
    if (!mb) {
      mb = import.meta.env.DEV ? "d00d00d00d00" : randomMailbox()
    }

    const effectiveHost = hostParam || defaultHost

    if (mb === activeMailboxRef.current && effectiveHost === activeHostRef.current) return

    setMailbox(mb)
    setHost(effectiveHost)
    setTimeout(() => connect({ mailbox: mb, host: effectiveHost, replace: true }), 0)
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [id, routeSearch])

  useEffect(() => {
    if (!wasmModule || !genMessage.trim() || !zone.trim()) {
      if (!genMessage.trim()) {
        setGenDomains([])
        setGenError("")
      }
      return
    }
    const mb = validateMailbox(mailbox)
    if (!mb) {
      setGenError("Mailbox must be exactly 12 lowercase hex characters")
      return
    }
    setGenError("")
    const timer = setTimeout(() => {
      try {
        const arr = wasmModule.domains_for_string_with_mailbox(genMessage, zone, mb)
        setGenDomains(Array.from(arr))
      } catch (e) {
        setGenError(String(e))
      }
    }, 100)
    return () => clearTimeout(timer)
  }, [wasmModule, genMessage, zone, mailbox])

  function toggleExpand(msgId: string) {
    setExpandedMessages((prev) => {
      const next = new Set(prev)
      if (next.has(msgId)) next.delete(msgId)
      else next.add(msgId)
      return next
    })
  }

  async function copyText(content: string) {
    try { await navigator.clipboard.writeText(content) } catch { /* ignore */ }
  }

  async function generateRandomMailbox() {
    const mb = randomMailbox()
    setMailbox(mb)
    await connect({ mailbox: mb })
  }

  const digCmd = `dig @${parentZone} -p 53 ${mailbox}.${mailboxZone} TXT +tcp +short`

  const statusDot = status.level === "good" ? "bg-green-500 shadow-[0_0_8px_rgba(34,197,94,0.5)]"
    : status.level === "warn" ? "bg-yellow-500 shadow-[0_0_8px_rgba(234,179,8,0.5)]"
    : status.level === "bad" ? "bg-red-500 shadow-[0_0_8px_rgba(239,68,68,0.5)]"
    : "bg-muted-foreground"

  return (
    <div className="max-w-[1100px] mx-auto p-5 md:p-7">
      <header className="flex items-center justify-between gap-4 mb-5 flex-wrap">
        <Link to="/" className="text-lg font-bold hover:opacity-80 transition-opacity">
          <span className="text-seagrass">dnsm</span> <span className="text-muted-foreground font-normal">// inbox</span>
        </Link>
        <div className="flex items-center gap-2 text-sm text-muted-foreground">
          <span className={`w-2 h-2 rounded-full ${statusDot}`} />
          <span>{status.text}</span>
        </div>
      </header>

      <Card className="p-4 mb-4">
        <div className="grid grid-cols-1 sm:grid-cols-[auto_1fr] gap-3 items-center">
          <label className="text-sm text-muted-foreground">WebSocket Server</label>
          <Input
            value={host}
            onChange={(e) => setHost(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && connect()}
            placeholder="localhost:8787 or ws.example.com"
            spellCheck={false}
          />
          <label className="text-sm text-muted-foreground">Mailbox</label>
          <div className="flex items-center gap-2 min-w-0">
            <Input
              value={mailbox}
              onChange={(e) => setMailbox(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && connect()}
              placeholder="12 hex chars, e.g. 50373ff32343"
              maxLength={12}
              spellCheck={false}
              className="flex-1 min-w-0"
            />
            <Button variant="outline" size="sm" onClick={generateRandomMailbox} className="shrink-0">
              <Shuffle className="h-3 w-3" /> Random
            </Button>
          </div>
        </div>

      </Card>

      <div className="flex items-center justify-between mb-3">
        <span className="text-sm text-muted-foreground">
          {messages.length} message{messages.length === 1 ? "" : "s"}
        </span>
        <Button
          variant="outline"
          size="sm"
          onClick={() => setMessages([])}
          disabled={messages.length === 0}
        >
          <Trash2 className="h-3 w-3" /> Clear
        </Button>
      </div>

      <div className="space-y-3">
        {messages.length === 0 ? (
          <div className="border border-dashed rounded-xl p-6 text-center text-muted-foreground">
            No messages yet. Send some data via dnsm with mailbox.
          </div>
        ) : (
          messages.map((msg) => (
            <MessageCard
              key={msg.id}
              msg={msg}
              expanded={expandedMessages.has(msg.id)}
              onToggle={() => toggleExpand(msg.id)}
              onCopy={copyText}
            />
          ))
        )}
      </div>

      <Collapsible title="Domain Generator" className="mt-4">
        <div className="grid grid-cols-1 sm:grid-cols-[auto_1fr] gap-3 items-center mb-3">
          <label className="text-sm text-muted-foreground">Zone</label>
          <Input
            value={zone}
            onChange={(e) => setZone(e.target.value)}
            placeholder="e.g. k.example.com"
            spellCheck={false}
          />
          <label className="text-sm text-muted-foreground">Message</label>
          <textarea
            value={genMessage}
            onChange={(e) => setGenMessage(e.target.value)}
            placeholder="Type or paste your message..."
            className="min-h-[100px] resize-y w-full rounded-md border border-input bg-transparent px-3 py-2 text-sm shadow-sm placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring font-mono"
          />
        </div>
        <div className="flex items-center gap-2 mb-2">
          <span className="text-xs text-muted-foreground">
            {wasmModule ? "Auto-generating as you type" : "Loading Wasm..."}
          </span>
          <span className="flex-1" />
          <Button
            variant="outline"
            size="sm"
            onClick={() => copyText(genDomains.join("\n"))}
            disabled={genDomains.length === 0}
          >
            <Copy className="h-3 w-3" /> Copy All
          </Button>
        </div>
        {genError && (
          <p className="text-xs text-destructive-foreground mb-2">{genError}</p>
        )}
        <div className="rounded-md border p-3 max-h-[300px] overflow-auto bg-background">
          {genDomains.length === 0 ? (
            <div className="text-center text-sm text-muted-foreground py-4 border border-dashed rounded-md">
              No domains yet. Enter zone and message. Mailbox: <code className="text-xs bg-secondary px-1 py-0.5 rounded">{mailbox || "(none)"}</code>
            </div>
          ) : (
            <ol className="list-decimal list-inside font-mono text-xs space-y-0.5">
              {genDomains.map((d, i) => <li key={i}>{d}</li>)}
            </ol>
          )}
        </div>
      </Collapsible>

      {mailbox && validateMailbox(mailbox) && (
        <Collapsible title="Retrieve via DNS" className="mt-4">
          <div className="flex items-center gap-2 py-2">
            <code className="flex-1 text-sm font-mono text-primary break-all">{digCmd}</code>
            <Button variant="ghost" size="icon" onClick={() => copyText(digCmd)} className="shrink-0">
              <Copy className="h-4 w-4" />
            </Button>
          </div>
        </Collapsible>
      )}

      <p className="mt-3 text-xs text-muted-foreground">
        API: GET <code className="text-xs bg-secondary px-1 py-0.5 rounded">/api/mailbox/{"{mailbox}"}/messages</code>, WS{" "}
        <code className="text-xs bg-secondary px-1 py-0.5 rounded">/ws/{"{mailbox}"}</code>. Returns messages in newest-first fashion + live push on new rows.
      </p>
    </div>
  )
}

function MessageCard({
  msg,
  expanded,
  onToggle,
  onCopy,
}: {
  msg: Message
  expanded: boolean
  onToggle: () => void
  onCopy: (text: string) => void
}) {
  const isPing = msg.payload.type === "ping"
  const long = !isPing && isLongContent(msg.payload.content)
  const isExpanded = !long || expanded

  return (
    <Card className={`px-3 pt-2 pb-5 ${isPing ? "border-atomic-tangerine/30" : ""}`}>
      <div className="flex flex-wrap items-baseline gap-2 text-xs font-mono pb-2 border-b border-border">
        {msg.message_hex && (
          <>
            <span className="text-muted-foreground uppercase tracking-wider text-[10px]">ID</span>
            <span className="break-all text-cerulean">{msg.message_hex}</span>
            <span className="text-border">•</span>
          </>
        )}
        <span className="text-muted-foreground uppercase tracking-wider text-[10px]">Received</span>
        <span className="text-willow-green">{formatReceivedAt(msg.received_at)}</span>
        <span className="text-border">•</span>
        <span className="text-muted-foreground uppercase tracking-wider text-[10px]">Type</span>
        <span className={isPing ? "text-atomic-tangerine" : "text-tuscan-sun"}>
          {isPing ? "ping" : msg.payload.type}
        </span>
        {msg.peer_ip && (
          <>
            <span className="text-border">•</span>
            <span className="text-muted-foreground uppercase tracking-wider text-[10px]">Peer</span>
            <span className="font-mono text-seagrass">{msg.peer_ip}</span>
          </>
        )}
        {!isPing && (
          <Button
            variant="ghost"
            size="sm"
            onClick={() => onCopy(msg.payload.content)}
            className="ml-auto h-6 w-6 p-0 [&_svg]:size-3"
            aria-label="Copy"
          >
            <Copy />
          </Button>
        )}
      </div>

      {!isPing && (
        <div className="mt-4">
          <div className={`relative ${!isExpanded ? "max-h-[200px] overflow-hidden" : ""}`}>
            <pre className="whitespace-pre-wrap break-words text-xs font-mono">{msg.payload.content}</pre>
            {!isExpanded && (
              <div className="absolute bottom-0 left-0 right-0 h-14 bg-gradient-to-t from-card to-transparent pointer-events-none" />
            )}
          </div>
          {long && (
            <div className="mt-2">
              <Button variant="ghost" size="sm" onClick={onToggle} className="h-6 px-2 text-[11px] gap-1 [&_svg]:size-3">
                <ChevronDown className={`transition-transform ${isExpanded ? "rotate-180" : ""}`} />
                {isExpanded ? "Show less" : "Show more"}
              </Button>
            </div>
          )}
        </div>
      )}
    </Card>
  )
}

// web/src/routes/Inbox.svelte
<script>
  import { onMount, onDestroy } from "svelte";
  import { link } from "svelte-spa-router";
  import { validateMailbox, randomMailbox } from "../lib/utils.js";

  let ws = null;
  let reconnectTimer = null;
  let reconnectDelay = 1000;
  const MAX_DELAY = 20000;
  let autoscroll = true;
  let autoReconnect = true;
  let messages = [];
  let status = { text: "Idle", level: "idle" };
  let host = location.hostname === "localhost" || location.hostname === "127.0.0.1" ? "127.0.0.1:8787" : "ws.dnsm.re";
  let mailbox = "";
  let zone = "k.dnsm.re";
  let wasmLoaded = false;
  let wasmModule = null;
  let genMessage = "";
  let genDomains = [];
  let genError = "";
  let genTimer = null;
  let generatorExpanded = false;
  let digExpanded = false;
  let expandedMessages = new Set();

  const COLLAPSE_LINE_THRESHOLD = 12;
  const COLLAPSE_CHAR_THRESHOLD = 1000;

  function isLongContent(content) {
    return content.length > COLLAPSE_CHAR_THRESHOLD ||
      content.split('\n').length > COLLAPSE_LINE_THRESHOLD;
  }

  function toggleExpand(id) {
    if (expandedMessages.has(id)) {
      expandedMessages.delete(id);
    } else {
      expandedMessages.add(id);
    }
    expandedMessages = expandedMessages;
  }

  $: parentZone = zone.split('.').slice(1).join('.') || zone;
  $: mailboxZone = `m.${parentZone}`;

  function toggleGenerator() {
    generatorExpanded = !generatorExpanded;
  }

  function toggleDig() {
    digExpanded = !digExpanded;
  }

  function setStatus(text, level = "idle") {
    status = { text, level };
  }

  function normalizeHttp(base, fallback) {
    const h = (base || "").trim();
    if (!h) return fallback;
    if (h.startsWith("http://") || h.startsWith("https://")) return h;
    if (h.includes("dnsm.re")) return "https://" + h;
    const scheme = location.protocol === "https:" ? "https://" : "http://";
    return scheme + h;
  }

  function toWsUrl(httpBase) {
    const u = new URL(httpBase);
    u.protocol = u.protocol === "https:" ? "wss:" : "ws:";
    return u.toString().replace(/\/$/, "");
  }

  function toHex(bytes) {
    let out = "";
    for (let i = 0; i < bytes.length; i++) {
      if (i && i % 16 === 0) out += "\n";
      else if (i && i % 2 === 0) out += " ";
      out += bytes[i].toString(16).padStart(2, "0");
    }
    return out;
  }

  function decodePayload(b64, messageType) {
    if (messageType === "ping") {
      return { type: "ping", content: "", raw: "" };
    }
    try {
      const bin = atob(b64);
      const bytes = new Uint8Array(bin.length);
      for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i) & 0xff;

      let text = null;
      try {
        text = new TextDecoder("utf-8", { fatal: true }).decode(bytes);
      } catch {}

      const printable = text && text.length > 0 && !/[\x00-\x08\x0b\x0c\x0e-\x1f]/.test(text);
      if (text && printable) {
        const trimmed = text.trim();
        if (
          (trimmed.startsWith("{") && trimmed.endsWith("}")) ||
          (trimmed.startsWith("[") && trimmed.endsWith("]"))
        ) {
          try {
            const parsed = JSON.parse(text);
            return {
              type: "json",
              content: JSON.stringify(parsed, null, 2),
              raw: b64,
            };
          } catch {}
        }
        return { type: "text", content: text, raw: b64 };
      }

      return { type: "binary", content: toHex(bytes), raw: b64 };
    } catch (e) {
      return { type: "invalid", content: `Invalid base64: ${e}`, raw: b64 };
    }
  }

  function formatDate(date) {
    const d = String(date.getDate()).padStart(2, "0");
    const m = String(date.getMonth() + 1).padStart(2, "0");
    const y = date.getFullYear();
    const H = String(date.getHours()).padStart(2, "0");
    const M = String(date.getMinutes()).padStart(2, "0");
    const S = String(date.getSeconds()).padStart(2, "0");
    return `${d}.${m}.${y}, ${H}:${M}:${S}`;
  }

  function computeReceivedMeta(value) {
    const numeric = typeof value === "number" ? value : Number(value);
    if (!Number.isFinite(numeric)) {
      const raw =
        value === null || value === undefined ? "Unknown" : String(value);
      return { label: "Unknown time", tooltip: raw };
    }
    const date = new Date(numeric);
    if (Number.isNaN(date.getTime())) {
      const raw =
        value === null || value === undefined ? "Unknown" : String(value);
      return { label: "Unknown time", tooltip: raw };
    }
    return { label: formatDate(date), tooltip: date.toISOString() };
  }

  function formatReceivedAt(value) {
    return computeReceivedMeta(value).label;
  }

  function receivedAtTooltip(value) {
    return computeReceivedMeta(value).tooltip;
  }

  async function fetchBacklog(httpBase, mb) {
    try {
      const url = `${httpBase.replace(/\/$/, "")}/api/mailbox/${mb}/messages`;
      const res = await fetch(url, { method: "GET" });
      if (!res.ok) {
        setStatus(`HTTP ${res.status}: failed to fetch`, "warn");
        return [];
      }
      const arr = await res.json();
      return Array.isArray(arr) ? arr : [];
    } catch (e) {
      setStatus(`HTTP error: ${e}`, "warn");
      return [];
    }
  }

  function scheduleReconnect() {
    if (!autoReconnect) return;
    if (reconnectTimer) clearTimeout(reconnectTimer);
    reconnectTimer = setTimeout(connect, reconnectDelay);
    reconnectDelay = Math.min(reconnectDelay * 2, MAX_DELAY);
    setStatus(
      `Reconnecting in ${Math.round(reconnectDelay / 1000)}s...`,
      "warn"
    );
  }

  let isConnected = false;
  let isIntentionalDisconnect = false;
  let isConnecting = false;

  async function connect() {
    const mb = validateMailbox(mailbox);
    if (!mb) {
      setStatus("Mailbox must be 12 lowercase hex chars", "bad");
      return;
    }

    // Prevent concurrent connection attempts
    if (isConnecting) {
      return;
    }

    isConnecting = true;
    isIntentionalDisconnect = true; // We're intentionally switching connections
    mailbox = mb;
    setStatus("Connecting...", "warn");
    messages = [];

    if (
      ws &&
      (ws.readyState === WebSocket.OPEN ||
        ws.readyState === WebSocket.CONNECTING)
    ) {
      try {
        ws.close();
      } catch {}
    }
    if (reconnectTimer) {
      clearTimeout(reconnectTimer);
      reconnectTimer = null;
    }
    reconnectDelay = 1000;

    const fallback =
      location.hostname && location.protocol.startsWith("http")
        ? `${location.protocol}//${location.host}`
        : "http://localhost:8787";
    const httpBase = normalizeHttp(host, fallback);
    const wsBase = toWsUrl(httpBase);

    const backlog = await fetchBacklog(httpBase, mb);
    messages = backlog.reverse().map((m) => ({
      ...m,
      payload: decodePayload(m.data_b64, m.message_type),
    }));

    try {
      ws = new WebSocket(`${wsBase}/ws/${mb}`);
    } catch (e) {
      setStatus(`WS init failed: ${e}`, "bad");
      isConnecting = false;
      scheduleReconnect();
      return;
    }

    ws.addEventListener("open", () => {
      setStatus("Connected to WebSocket server", "good");
      isConnected = true;
      isConnecting = false;
      isIntentionalDisconnect = false; // Reset the flag on successful connection
      reconnectDelay = 1000; // Reset delay on successful connection
    });
    ws.addEventListener("close", () => {
      setStatus("Disconnected", "warn");
      isConnected = false;
      isConnecting = false;

      // Only auto-reconnect if this wasn't an intentional disconnect
      if (!isIntentionalDisconnect) {
        scheduleReconnect();
      } else {
        // Reset the flag for future disconnects
        isIntentionalDisconnect = false;
      }
    });
    ws.addEventListener("error", () => {
      setStatus("WebSocket error", "bad");
      isConnecting = false;
    });
    ws.addEventListener("message", (ev) => {
      try {
        const m = JSON.parse(ev.data);
        const msg = { ...m, payload: decodePayload(m.data_b64, m.message_type) };
        messages = [...messages, msg];
        if (autoscroll) {
          setTimeout(() => {
            const stream = document.getElementById("stream");
            if (stream) stream.scrollTop = stream.scrollHeight;
          }, 100);
        }
      } catch {}
    });
  }

  function clearMessages() {
    messages = [];
  }

  async function generateRandomMailbox() {
    mailbox = randomMailbox();
    // Reconnect with the new mailbox
    await connect();
  }

  async function copyText(content) {
    try {
      await navigator.clipboard.writeText(content);
    } catch (e) {
      console.error("Copy failed:", e);
    }
  }

  function applyQueryParams() {
    // Parse query params from hash (e.g., #/inbox?mailbox=abc&host=xyz)
    const hashParts = location.hash.split("?");
    const queryString = hashParts.length > 1 ? hashParts[1] : "";
    const p = new URLSearchParams(queryString);
    const hostParam = p.get("host");
    const mailboxParam = p.get("mailbox");
    const auto = p.get("auto");
    if (hostParam) host = hostParam;
    if (mailboxParam) mailbox = mailboxParam;
    if (auto === "0" || auto === "false") autoReconnect = false;
    return (hostParam && mailboxParam) || auto === "1" || auto === "true";
  }

  async function loadWasm() {
    try {
      if (!wasmModule) {
        wasmModule = await import("../lib/pkg-web/dnsm.js");
        await wasmModule.default();
      }
      wasmLoaded = true;
    } catch (e) {
      console.error("Failed to load Wasm module:", e);
    }
  }

  function ensureMailboxForGen() {
    const v = (mailbox || "").trim();
    if (v === "") return "";
    const ok = validateMailbox(v);
    if (!ok) return null;
    return ok;
  }

  async function generateDomains() {
    genError = "";
    genDomains = [];
    if (!wasmLoaded) await loadWasm();
    const mb = ensureMailboxForGen();
    if (mb === null) {
      genError = "Mailbox must be exactly 12 lowercase hex characters";
      return;
    }
    const z = (zone || "").trim();
    const msg = (genMessage || "").toString();
    if (!z || !msg) {
      return;
    }
    try {
      const arr = wasmModule.domains_for_string_with_mailbox(msg, z, mb);
      genDomains = Array.from(arr);
    } catch (e) {
      genError = String(e);
    }
  }

  // Auto-generate on changes with a small debounce
  $: (async () => {
    if (!wasmLoaded || !generatorExpanded) return;
    if (genTimer) {
      clearTimeout(genTimer);
      genTimer = null;
    }
    const msgOk = (genMessage || "").trim().length > 0;
    const zOk = (zone || "").trim().length > 0;
    const mb = ensureMailboxForGen();
    if (!msgOk || !zOk || mb === null) {
      if (!msgOk) {
        genDomains = [];
        genError = "";
      }
      return;
    }
    genTimer = setTimeout(() => {
      generateDomains();
    }, 100);
  })();

  async function copyAllGenerated() {
    try {
      await navigator.clipboard.writeText(genDomains.join("\n"));
    } catch (e) {
      genError = `Copy failed: ${e}`;
    }
  }

  onMount(() => {
    // Apply query params first to get mailbox from URL if present
    applyQueryParams();
    // If no mailbox was set from query params, use a fixed dev mailbox or random
    if (!mailbox) {
      mailbox = import.meta.env.DEV ? "d00d00d00d00" : randomMailbox();
    }
    // Preload WASM for generator
    loadWasm();
    // Auto-connect on load
    connect();
  });

  onDestroy(() => {
    // Disable auto-reconnect when component is being destroyed
    autoReconnect = false;
    isConnecting = false;
    isIntentionalDisconnect = true;

    if (ws) {
      try {
        ws.close();
      } catch {}
    }
    if (reconnectTimer) {
      clearTimeout(reconnectTimer);
      reconnectTimer = null;
    }
  });
</script>

<div class="wrap">
  <header>
    <div class="brand">
      <a href="#/" use:link class="logo"
        >dnsm <span class="muted">// inbox</span></a
      >
    </div>
    <div class="stat" title="Connection status">
      <span
        class="dot"
        class:good={status.level === "good"}
        class:warn={status.level === "warn"}
        class:bad={status.level === "bad"}
      ></span>
      <span>{status.text}</span>
    </div>
  </header>

  <section class="panel" aria-label="Connection">
    <div class="controls">
      <label for="host">WebSocket Server</label>
      <input
        id="host"
        type="text"
        spellcheck="false"
        placeholder="localhost:8787 or ws.example.com"
        bind:value={host}
        on:keydown={(e) => e.key === "Enter" && connect()}
      />
      <label for="mailbox">Mailbox</label>
      <input
        id="mailbox"
        type="text"
        spellcheck="false"
        placeholder="12 hex chars, e.g. 50373ff32343"
        maxlength="12"
        bind:value={mailbox}
        on:keydown={(e) => e.key === "Enter" && connect()}
      />
    </div>

    <div
      class="collapsible-header"
      role="button"
      tabindex="0"
      on:click={toggleGenerator}
      on:keydown={(e) => (e.key === 'Enter' || e.key === ' ') && toggleGenerator()}
    >
      <span class="collapsible-title">Domain Generator</span>
      <svg
        class="chevron"
        class:expanded={generatorExpanded}
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
      >
        <polyline points="6 9 12 15 18 9"></polyline>
      </svg>
    </div>

    {#if generatorExpanded}
      <div class="generator-section">
        <div class="controls" style="margin-bottom: 14px;">
          <label for="gen-zone">Zone</label>
          <input
            id="gen-zone"
            type="text"
            spellcheck="false"
            placeholder="e.g. k.example.com"
            bind:value={zone}
          />
          <label for="gen-message">Message</label>
          <textarea
            id="gen-message"
            class="msg-input"
            placeholder="Type or paste your message..."
            bind:value={genMessage}
          ></textarea>
        </div>
        <div class="toolbar" style="margin-bottom: 10px;">
          <span class="muted small"
            >{wasmLoaded
              ? "Auto-generating as you type"
              : "Loading Wasm..."}</span
          >
          <div class="spacer"></div>
          <button
            class="btn small"
            on:click={copyAllGenerated}
            disabled={genDomains.length === 0}>Copy All</button
          >
        </div>
        {#if genError}
          <p class="hint" style="color: var(--danger); margin-top: 0; margin-bottom: 10px;">{genError}</p>
        {/if}
        <div class="gen-out">
          {#if genDomains.length === 0}
            <div class="empty">
              No domains yet. Enter zone and message. Mailbox: <code
                >{mailbox || "(none)"}</code
              >
            </div>
          {:else}
            <ol class="gen-list">
              {#each genDomains as d}
                <li><code>{d}</code></li>
              {/each}
            </ol>
          {/if}
        </div>
      </div>
    {/if}

    <div class="toolbar" style="margin-top: 10px;">
      <button
        on:click={generateRandomMailbox}
        class="btn btn-secondary small"
        title="Generate random mailbox">Random Mailbox</button
      >
      <div class="spacer"></div>
      <button
        on:click={() => (autoscroll = !autoscroll)}
        class="btn small"
        class:btn-secondary={!autoscroll}
        title="Toggle autoscroll"
      >
        Autoscroll: {autoscroll ? "On" : "Off"}
      </button>
      <button
        on:click={() => (autoReconnect = !autoReconnect)}
        class="btn small"
        class:btn-secondary={!autoReconnect}
        title="Toggle auto-reconnect"
      >
        Auto-Reconnect: {autoReconnect ? "On" : "Off"}
      </button>
      <button
        on:click={clearMessages}
        class="btn btn-secondary small"
        title="Clear messages"
        disabled={messages.length === 0}>Clear</button
      >
    </div>
  </section>

  <section class="stream" id="stream" aria-live="polite">
    <div class="stream-inner">
    {#if messages.length === 0}
      <div class="empty">
        No messages yet. Send some data via dnsm with mailbox.
      </div>
    {:else}
      {#each messages as msg (msg.id)}
        <div class="msg" class:msg-ping={msg.payload.type === "ping"}>
          <div class="row">
            <div class="meta">
              <div class="meta-line">
                {#if msg.message_hex}
                  <span class="meta-label">Message ID</span>
                  <span class="meta-value mono mono-break"
                    >{msg.message_hex}</span
                  >
                  <span class="meta-sep">•</span>
                {/if}
                <span class="meta-label">Received</span>
                <span
                  class="meta-value"
                  title={receivedAtTooltip(msg.received_at)}
                >
                  {formatReceivedAt(msg.received_at)}
                </span>
                <span class="meta-sep">•</span>
                <span class="meta-label">Type</span>
                <span class="meta-value">
                  <span class="badge" class:badge-ping={msg.payload.type === "ping"}>{msg.payload.type === "ping" ? "Ping" : msg.payload.type}</span>
                </span>
                {#if msg.peer_ip}
                  <span class="meta-sep">•</span>
                  <span class="meta-label">Peer</span>
                  <span class="meta-value mono">{msg.peer_ip}</span>
                {/if}
              </div>
            </div>
          </div>
          {#if msg.payload.type !== "ping"}
            {@const long = isLongContent(msg.payload.content)}
            {@const expanded = !long || expandedMessages.has(msg.id)}
            <div class="payload-section">
              <div class="payload-wrap" class:collapsed={!expanded}>
                {#if msg.payload.type === "json"}
                  <pre class="payload mono">{msg.payload.content}</pre>
                {:else if msg.payload.type === "binary"}
                  <pre class="payload mono">{msg.payload.content}</pre>
                {:else}
                  <div class="payload">{msg.payload.content}</div>
                {/if}
                {#if !expanded}
                  <div class="fade-overlay"></div>
                {/if}
              </div>
              <div class="toolbar" style="margin-top: 8px;">
                {#if long}
                  <button
                    on:click={() => toggleExpand(msg.id)}
                    class="iconbtn small"
                    title={expanded ? "Collapse message" : "Expand message"}
                  >
                    <svg
                      class="icon chevron-icon"
                      class:expanded
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      stroke-width="2"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      aria-hidden="true"
                    >
                      <polyline points="6 9 12 15 18 9"></polyline>
                    </svg>
                    {expanded ? 'Show less' : 'Show more'}
                  </button>
                {/if}
                <button
                  on:click={() => copyText(msg.payload.content)}
                  class="iconbtn small"
                  title="Copy as text"
                >
                  <svg
                    class="icon"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="1.7"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    aria-hidden="true"
                  >
                    <rect x="9" y="9" width="13" height="13" rx="2"></rect>
                    <path d="M5 15V5a2 2 0 0 1 2-2h10" />
                  </svg>
                  Copy
                </button>
              </div>
            </div>
          {/if}
        </div>
      {/each}
    {/if}
    </div>
  </section>

  {#if mailbox && validateMailbox(mailbox)}
    <div class="dig-section">
      <div
        class="dig-header"
        role="button"
        tabindex="0"
        on:click={toggleDig}
        on:keydown={(e) => (e.key === 'Enter' || e.key === ' ') && toggleDig()}
      >
        <span class="dig-title">Retrieve via DNS</span>
        <svg
          class="chevron"
          class:expanded={digExpanded}
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <polyline points="6 9 12 15 18 9"></polyline>
        </svg>
      </div>
      {#if digExpanded}
        <div class="dig-content">
          <div class="dig-cmd">
            <code>dig @{parentZone} -p 53 {mailbox}.{mailboxZone} TXT +tcp +short</code>
            <button
              class="dig-copy-btn"
              on:click={() => copyText(`dig @${parentZone} -p 53 ${mailbox}.${mailboxZone} TXT +tcp +short`)}
              title="Copy command"
              aria-label="Copy dig command"
            >
              <svg
                class="icon"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="1.7"
                stroke-linecap="round"
                stroke-linejoin="round"
                aria-hidden="true"
              >
                <rect x="9" y="9" width="13" height="13" rx="2"></rect>
                <path d="M5 15V5a2 2 0 0 1 2-2h10" />
              </svg>
            </button>
          </div>
        </div>
      {/if}
    </div>
  {/if}

  <p class="hint small">
    API: GET <code>/api/mailbox/&#123;mailbox&#125;/messages</code>, WS
    <code>/ws/&#123;mailbox&#125;</code>. Returns messages in newest-first
    fashion + live push on new rows.
  </p>
</div>

<style>
  .collapsible-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 12px 14px;
    margin-top: 10px;
    background: linear-gradient(135deg, #0a0e13 0%, #0d1218 100%);
    border: 1px solid var(--border);
    border-radius: var(--radius-sm);
    cursor: pointer;
    user-select: none;
    transition: all 0.2s ease;
    outline: none;
  }

  .collapsible-header:hover {
    border-color: rgba(29, 242, 166, 0.3);
    background: linear-gradient(135deg, #0c1015 0%, #0f141a 100%);
    box-shadow: inset 0 0 0 1px rgba(29, 242, 166, 0.1);
  }

  .collapsible-header:focus-visible {
    border-color: var(--accent);
    box-shadow: 0 0 0 3px rgba(29, 242, 166, 0.15);
  }

  .collapsible-title {
    font-size: 13px;
    font-weight: 600;
    color: var(--text);
    display: flex;
    align-items: center;
    gap: 8px;
  }

  .collapsible-title::before {
    content: '⚙️';
    font-size: 14px;
  }

  .chevron {
    width: 18px;
    height: 18px;
    color: var(--accent);
    transition: all 0.2s ease;
  }

  .collapsible-header:hover .chevron {
    color: var(--accent-2);
  }

  .chevron.expanded {
    transform: rotate(180deg);
  }

  .generator-section {
    margin-top: 12px;
    padding: 16px;
    background: linear-gradient(180deg, #080c10 0%, #0a0e13 100%);
    border: 1px solid var(--border);
    border-radius: var(--radius-sm);
    box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.3);
  }

  .stream {
    max-height: 60vh;
    overflow-y: auto;
    -webkit-overflow-scrolling: touch;
  }

  .stream-inner {
    display: grid;
    gap: 12px;
    padding-right: 8px;
  }

  .msg {
    border: 1px solid rgba(35, 52, 64, 0.7);
    border-radius: var(--radius);
    background: #0b1319;
    padding: 12px 16px;
    box-shadow: inset 0 0 0 1px rgba(16, 27, 36, 0.4);
  }

  .msg-ping {
    border-color: rgba(139, 92, 246, 0.35);
    background: linear-gradient(135deg, #0d0b19 0%, #0b1319 100%);
    box-shadow: inset 0 0 0 1px rgba(139, 92, 246, 0.1), 0 0 12px rgba(139, 92, 246, 0.06);
  }

  .badge-ping {
    color: #c4b5fd !important;
    background: rgba(139, 92, 246, 0.15) !important;
    border-color: rgba(139, 92, 246, 0.3) !important;
  }

  .msg .row {
    margin-bottom: 8px;
  }

  .msg .row:last-child {
    margin-bottom: 0;
  }

  .meta {
    display: flex;
    flex-direction: column;
    gap: 4px;
    font-family: var(--font-mono);
  }

  .meta-line {
    display: flex;
    flex-wrap: wrap;
    gap: 8px;
    align-items: baseline;
  }

  .meta-label {
    text-transform: uppercase;
    font-size: 10px;
    letter-spacing: 0.08em;
    color: #6e7c8d;
    white-space: nowrap;
  }

  .meta-value {
    font-size: 12px;
    color: #d6e2f1;
    white-space: nowrap;
  }

  .meta-value.mono {
    font-family: var(--font-mono);
  }

  .meta-value.mono-break {
    font-family: var(--font-mono);
    white-space: normal;
    word-break: break-all;
  }

  .meta-sep {
    color: #354250;
  }

  .meta-line .badge {
    font-size: 10px;
    letter-spacing: 0.08em;
    text-transform: uppercase;
    padding: 2px 6px;
  }

  .payload-section {
    margin-top: 8px;
  }

  .payload-wrap {
    position: relative;
  }

  .payload-wrap.collapsed {
    max-height: 200px;
    overflow: hidden;
  }

  .fade-overlay {
    position: absolute;
    bottom: 0;
    left: 0;
    right: 0;
    height: 60px;
    background: linear-gradient(transparent, #0b1319);
    pointer-events: none;
  }

  .chevron-icon {
    transition: transform 0.2s ease;
  }

  .chevron-icon.expanded {
    transform: rotate(180deg);
  }

  .iconbtn {
    cursor: pointer;
    color: var(--muted);
    border: 1px solid var(--border);
    background: #0c1217;
    border-radius: var(--radius-sm);
    padding: 6px 8px;
    display: inline-flex;
    gap: 8px;
    align-items: center;
    font-family: var(--font-mono);
    font-size: 12px;
    transition: all 0.2s ease;
  }

  .iconbtn:hover {
    color: var(--accent);
    border-color: #204b3f;
    box-shadow: inset 0 0 0 1px rgba(29, 242, 166, 0.15);
  }

  .icon {
    width: 14px;
    height: 14px;
    display: inline-block;
    flex-shrink: 0;
  }

  .logo {
    text-decoration: none;
    color: var(--accent);
    transition: opacity 0.2s ease;
  }

  .logo:hover {
    opacity: 0.8;
  }

  .msg-input {
    min-height: 120px;
    resize: vertical;
    background: #0b1219;
    color: var(--text);
    border: 1px solid var(--border);
    border-radius: var(--radius-sm);
    padding: 10px 12px;
    outline: none;
    transition:
      border-color 0.15s ease,
      box-shadow 0.15s ease;
    font-family: var(--font-mono);
  }

  .msg-input:focus {
    border-color: var(--accent);
    box-shadow: 0 0 0 3px rgba(29, 242, 166, 0.15);
  }

  .gen-out {
    margin-top: 10px;
    background: #0b1016;
    border: 1px solid var(--border);
    border-radius: var(--radius-sm);
    padding: 10px;
    max-height: 320px;
    overflow: auto;
  }

  .gen-list {
    margin: 0;
    padding-left: 20px;
    font-family: var(--font-mono);
    font-size: 12px;
    color: var(--text);
  }

  .dig-section {
    margin-top: 16px;
    margin-bottom: 12px;
  }

  .dig-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 10px 12px;
    background: linear-gradient(135deg, #0a0e13 0%, #0d1218 100%);
    border: 1px solid var(--border);
    border-radius: var(--radius-sm);
    cursor: pointer;
    user-select: none;
    transition: all 0.2s ease;
    outline: none;
  }

  .dig-header:hover {
    border-color: rgba(29, 242, 166, 0.3);
    background: linear-gradient(135deg, #0c1015 0%, #0f141a 100%);
    box-shadow: inset 0 0 0 1px rgba(29, 242, 166, 0.1);
  }

  .dig-header:focus-visible {
    border-color: var(--accent);
    box-shadow: 0 0 0 3px rgba(29, 242, 166, 0.15);
  }

  .dig-header .chevron {
    width: 18px;
    height: 18px;
    color: var(--accent);
    transition: all 0.2s ease;
  }

  .dig-header:hover .chevron {
    color: var(--accent-2);
  }

  .dig-header .chevron.expanded {
    transform: rotate(180deg);
  }

  .dig-title {
    font-size: 13px;
    font-weight: 600;
    color: var(--text);
  }

  .dig-content {
    margin-top: 8px;
    padding: 10px 12px;
    background: linear-gradient(180deg, #080c10 0%, #0a0e13 100%);
    border: 1px solid var(--border);
    border-radius: var(--radius-sm);
    box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.3);
  }

  .dig-cmd {
    display: flex;
    align-items: center;
    gap: 8px;
    background: #0b1016;
    border: 1px solid var(--border);
    border-radius: var(--radius-sm);
    padding: 8px 10px;
  }

  .dig-cmd code {
    flex: 1;
    font-family: var(--font-mono);
    font-size: 12px;
    color: var(--accent);
    word-break: break-all;
  }

  .dig-copy-btn {
    background: transparent;
    border: none;
    cursor: pointer;
    padding: 4px;
    display: flex;
    align-items: center;
    justify-content: center;
    color: var(--muted);
    border-radius: 4px;
    transition: all 0.2s ease;
    flex-shrink: 0;
  }

  .dig-copy-btn:hover {
    color: var(--accent);
    background: rgba(29, 242, 166, 0.08);
  }

  .dig-copy-btn .icon {
    width: 14px;
    height: 14px;
    display: block;
  }
</style>
