// web/src/App.tsx
import { Routes, Route } from "react-router-dom"
import { Splash } from "@/pages/Splash"
import { Inbox } from "@/pages/Inbox"
import { BrowserTest } from "@/pages/BrowserTest"

export default function App() {
  return (
    <Routes>
      <Route path="/" element={<Splash />} />
      <Route path="/inbox" element={<Inbox />} />
      <Route path="/inbox/:id" element={<Inbox />} />
      <Route path="/browser-test" element={<BrowserTest />} />
    </Routes>
  )
}

// web/src/App.svelte
<script>
  import Router from 'svelte-spa-router';
  import Splash from './routes/Splash.svelte';
  import Inbox from './routes/Inbox.svelte';
  import BrowserTest from './routes/BrowserTest.svelte';

  const routes = {
    '/': Splash,
    '/inbox': Inbox,
    '/browser-test': BrowserTest,
  };
</script>

<Router {routes} />
